// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmN9YOs_kRgF2L2GVFme1EmSqk4la-1i8',
    appId: '1:125091434839:web:d6bf8f412cb0e10f4a2e12',
    messagingSenderId: '125091434839',
    projectId: 'asistencia-personal-b0674',
    authDomain: 'asistencia-personal-b0674.firebaseapp.com',
    storageBucket: 'asistencia-personal-b0674.firebasestorage.app',
    measurementId: 'G-VQ0QPPLFSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4_KsvvXxAKLhJP6N4PkOf5BTdzyC1hSY',
    appId: '1:125091434839:android:179e7677d7f17eeb4a2e12',
    messagingSenderId: '125091434839',
    projectId: 'asistencia-personal-b0674',
    storageBucket: 'asistencia-personal-b0674.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcxM4XAF8zLgOyj0wBmkCKBiEylzmwZ7o',
    appId: '1:125091434839:ios:663c8b39f18353ae4a2e12',
    messagingSenderId: '125091434839',
    projectId: 'asistencia-personal-b0674',
    storageBucket: 'asistencia-personal-b0674.firebasestorage.app',
    iosBundleId: 'com.lasalle.asistenciapersonal1',
  );
}
